// alpha.mjs — the entry point. One command answers: what is the true state of this
// agent runtime, and is the agent currently living up to what it has learned?
//
//   node alpha.mjs             measure, verdict, regenerate brief.md
//   node alpha.mjs --json      machine-readable
//   node alpha.mjs --test      self-test the toolkit against the live trace
//   node alpha.mjs --no-write  skip writing brief.md / the learning ledger

import { writeFileSync, existsSync, appendFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { analyse, render as renderAnalysis } from "./toolkit/analyze.mjs";
import { cycle, render as renderVerdict } from "./toolkit/learn.mjs";
import { selfTest } from "./toolkit/selftest.mjs";
import { archiveRollouts, ROLLOUT_DIR } from "./toolkit/trace.mjs";
import { resumePlan, render as renderResume } from "./toolkit/resume.mjs";
import { efficacy, render as renderEfficacy } from "./toolkit/efficacy.mjs";

const ROOT = dirname(fileURLToPath(import.meta.url));
const BRIEF = join(ROOT, "brief.md");
const RAW = join(ROOT, "raw");
const LEDGER = join(ROOT, "memory", "learnings.jsonl");

const n = (x) => (x ?? 0).toLocaleString();

function buildBrief(a, c, arch) {
  const t = a.totals;
  const worst = [...a.sessions].sort((x, y) => (y.cost.billedRatio ?? 0) - (x.cost.billedRatio ?? 0))[0];
  return `# ALPHA — generated brief

> Generated by \`node alpha.mjs\`. Do not edit by hand; it is overwritten every run.
> Measured ${new Date().toISOString()} · ${t.calls} model calls · evidence snapshot: ${arch.archived} new, ${arch.kept} already held in \`raw/\`.

## The runtime, measured

| | |
|---|---|
| models | ${t.models.join(", ")} |
| model calls | ${t.calls} (${t.scored} with usage) · ${t.errors} errors · ${t.retries} retries |
| input, raw | ${n(t.input)} |
| &nbsp;&nbsp;of which cache re-read | ${n(t.cacheRead)} (**${t.cacheHitShare}%**) |
| &nbsp;&nbsp;**fresh / computed** | **${n(t.billedInput)}** |
| output | ${n(t.output)} (${n(t.reasoning)} reasoning) |
| ratio | ${t.ratio}:1 raw — **${t.billedRatio}:1 on fresh input** |
| tool schema floor | ${a.schema.floorTokens ? n(a.schema.floorTokens) : "?"} tokens carried on every call |
| unused tools | ${a.schema.neverUsed.length} never invoked = ${n(a.schema.neverUsedTokens)}/call (${a.schema.neverUsedShare}% of floor) |

> The raw ratio is dominated by cache re-reads and is **not** a measure of waste or cost.
> The only honest measure of work done is \`fresh input / output\`.

## Sessions

| session | kind | calls | fresh in | out | fresh:out | raw | cache |
|---|---|---|---|---|---|---|---|
${a.sessions.map((s) => `| \`${s.sessionId.slice(0, 26)}\` | ${s.kind} | ${s.cost.callCount} | ${n(s.cost.billedInput)} | ${n(s.cost.totalOut)} | ${s.cost.billedRatio}:1 | ${s.cost.rawRatio}:1 | ${s.cost.cacheHitShare}% |`).join("\n")}

${worst && (worst.cost.billedRatio ?? 0) > 12 ? `> Worst fresh-input yield: \`${worst.sessionId.slice(0, 26)}\` at **${worst.cost.billedRatio}:1**.\n` : ""}
## Rules: ${c.record.verdict}

${c.verdicts.map((v) => {
  const tag = v.status === "holding" ? "OK" : v.status === "standing" ? "stated" : v.status === "violated" ? "**BREACH**" : "BROKEN";
  return `- \`${v.id}\` **${tag}** — ${v.title}${v.detail ? `\n  - ${v.detail}` : ""}`;
}).join("\n")}

${c.uncovered.length ? `\n## Uncovered findings — no rule claims these yet\n\n${c.uncovered.map((f) => `- **${f.id}**: ${f.claim}`).join("\n")}\n` : ""}
## Regenerate

\`node alpha.mjs\` · verify with \`node toolkit/selftest.mjs\`
`;
}

const argv = process.argv.slice(2);

if (argv.includes("--test")) {
  const ok = selfTest();
  process.exit(ok ? 0 : 1);
}

if (argv.includes("--resume")) {
  // The always-on entry point. Run this first after any interruption: it says what died,
  // why, and what was in flight. It never halts — an interrupted session is work to do.
  const plan = resumePlan();
  console.log(process.argv.includes("--json") ? JSON.stringify(plan, null, 2) : renderResume(plan));
  process.exit(0);
}

// Snapshot first: ZCode deletes a sub-agent's rollout file when the session ends, and any
// rule citing that session loses its evidence within minutes.
const arch = archiveRollouts(RAW, ROLLOUT_DIR);

const a = analyse();
const c = cycle({ scope: argv.includes("--all") ? "all" : "latest" });

if (!argv.includes("--no-write")) {
  mkdirSync(dirname(LEDGER), { recursive: true });
  writeFileSync(BRIEF, buildBrief(a, c, arch), "utf8");
  appendFileSync(LEDGER, JSON.stringify(c.record) + "\n");
}

if (argv.includes("--json")) {
  console.log(JSON.stringify({ measured: a.totals, schema: a.schema, sessions: a.sessions.map((s) => ({ ...s, calls: undefined })), verdict: c.record }, null, 2));
} else {
  console.log(renderAnalysis(a));
  console.log("\n" + "=".repeat(72) + "\n");
  console.log(renderVerdict(c));
  // Always-on: every run reports what was left unfinished, so a session that resumed after
  // a network drop cannot mistake an interrupted turn for a completed one.
  const rp = resumePlan();
  console.log("\n" + "=".repeat(72) + "\n");
  console.log(renderResume(rp));
  console.log(`\nbrief.md ${argv.includes("--no-write") ? "(not written)" : "regenerated"} | learnings.jsonl ${argv.includes("--no-write") ? "(not appended)" : "appended"}`);
}